// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMTTQ.Models;

#nullable disable

namespace WebMTTQ.Migrations
{
    [DbContext(typeof(DataMTTQContext))]
    [Migration("20260722084649_ThongTinUngHo")]
    partial class ThongTinUngHo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebMTTQ.Models.BaiViet", b =>
                {
                    b.Property<int>("IdbaiViet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDBaiViet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdbaiViet"));

                    b.Property<byte[]>("AnhDaiDien")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool?>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("IdchuyenMuc")
                        .HasColumnType("int")
                        .HasColumnName("IDChuyenMuc");

                    b.Property<int?>("IdnguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("IDNguoiDung");

                    b.Property<bool?>("LaTinNoiBat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("LuotXem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("NgayXuatBan")
                        .HasColumnType("datetime");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TomTat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("BanNhap");

                    b.HasKey("IdbaiViet")
                        .HasName("PK__BaiViet__FC50A207B66391FD");

                    b.HasIndex("IdchuyenMuc");

                    b.HasIndex("IdnguoiDung");

                    b.HasIndex(new[] { "DaXoa" }, "IDX_BaiViet_DaXoa");

                    b.HasIndex(new[] { "DuongDan" }, "IDX_BaiViet_DuongDan");

                    b.ToTable("BaiViet");
                });

            modelBuilder.Entity("WebMTTQ.Models.CauHinhHeThong", b =>
                {
                    b.Property<int>("IdcauHinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDCauHinh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdcauHinh"));

                    b.Property<string>("GiaTriCauHinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCauHinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdcauHinh")
                        .HasName("PK__CauHinhH__DE9A3B7A3F70271C");

                    b.HasIndex(new[] { "MaCauHinh" }, "UQ__CauHinhH__F0685B7C0CDBF0F8")
                        .IsUnique();

                    b.ToTable("CauHinhHeThong");
                });

            modelBuilder.Entity("WebMTTQ.Models.ChuongTrinhHoTro", b =>
                {
                    b.Property<int>("IdchuongTrinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDChuongTrinh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdchuongTrinh"));

                    b.Property<bool?>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LoaiHinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChuongTrinh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("DangTrienKhai");

                    b.HasKey("IdchuongTrinh")
                        .HasName("PK__ChuongTr__7B0509A41C0A9DEB");

                    b.ToTable("ChuongTrinhHoTro");
                });

            modelBuilder.Entity("WebMTTQ.Models.ChuyenMuc", b =>
                {
                    b.Property<int>("IdchuyenMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDChuyenMuc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdchuyenMuc"));

                    b.Property<bool?>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("IdchuyenMucCha")
                        .HasColumnType("int")
                        .HasColumnName("IDChuyenMucCha");

                    b.Property<string>("LoaiChuyenMuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenChuyenMuc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ThuTu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("IdchuyenMuc")
                        .HasName("PK__ChuyenMu__1078CD135189713F");

                    b.HasIndex("IdchuyenMucCha");

                    b.HasIndex(new[] { "DuongDan" }, "IDX_ChuyenMuc_DuongDan");

                    b.ToTable("ChuyenMuc");
                });

            modelBuilder.Entity("WebMTTQ.Models.DanhMucQuy", b =>
                {
                    b.Property<int>("Idquy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDQuy");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idquy"));

                    b.Property<bool?>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TenQuy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("TonQuy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("TongChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("TongThu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 0)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("HoatDong");

                    b.HasKey("Idquy")
                        .HasName("PK__DanhMucQ__A743077E0D5CACAF");

                    b.ToTable("DanhMucQuy");
                });

            modelBuilder.Entity("WebMTTQ.Models.DiaDiemBanDo", b =>
                {
                    b.Property<int>("IddiaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDDiaDiem");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IddiaDiem"));

                    b.Property<bool?>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("HinhAnhThucTe")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("IddonVi")
                        .HasColumnType("int")
                        .HasColumnName("IDDonVi");

                    b.Property<decimal>("KinhDo")
                        .HasColumnType("decimal(10, 8)");

                    b.Property<string>("MoTaChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanLoaiBanDo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDiaDiem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ThongTinLienHe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("HienThi");

                    b.Property<decimal>("ViDo")
                        .HasColumnType("decimal(10, 8)");

                    b.HasKey("IddiaDiem")
                        .HasName("PK__DiaDiemB__3DD0D654483F5641");

                    b.HasIndex("IddonVi");

                    b.HasIndex(new[] { "DaXoa" }, "IDX_DiaDiemBanDo_DaXoa");

                    b.ToTable("DiaDiemBanDo");
                });

            modelBuilder.Entity("WebMTTQ.Models.DoanTheToChuc", b =>
                {
                    b.Property<int>("IddonVi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDDonVi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IddonVi"));

                    b.Property<bool?>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("LogoDaiDien")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MauSacHienThi")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenDonVi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IddonVi")
                        .HasName("PK__DoanTheT__082302BFBA08A593");

                    b.ToTable("DoanTheToChuc");
                });

            modelBuilder.Entity("WebMTTQ.Models.DonXinHoTro", b =>
                {
                    b.Property<int>("Iddon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDDon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Iddon"));

                    b.Property<bool?>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HoTenNguoiGui")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("IdnguoiCanGiup")
                        .HasColumnType("int")
                        .HasColumnName("IDNguoiCanGiup");

                    b.Property<int?>("IdnguoiXuLy")
                        .HasColumnType("int")
                        .HasColumnName("IDNguoiXuLy");

                    b.Property<string>("MucDoUuTien")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("BinhThuong");

                    b.Property<DateTime?>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ChoXuLy");

                    b.HasKey("Iddon")
                        .HasName("PK__DonXinHo__93E3A4198A461737");

                    b.HasIndex("IdnguoiCanGiup");

                    b.HasIndex("IdnguoiXuLy");

                    b.ToTable("DonXinHoTro");
                });

            modelBuilder.Entity("WebMTTQ.Models.HopThuGopY", b =>
                {
                    b.Property<int>("IdgopY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDGopY");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdgopY"));

                    b.Property<bool?>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdnguoiXuLy")
                        .HasColumnType("int")
                        .HasColumnName("IDNguoiXuLy");

                    b.Property<DateTime?>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungPhanHoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<byte[]>("TepMinhChung")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ChoXuLy");

                    b.HasKey("IdgopY")
                        .HasName("PK__HopThuGo__D232A95EF309C612");

                    b.HasIndex("IdnguoiXuLy");

                    b.ToTable("HopThuGopY");
                });

            modelBuilder.Entity("WebMTTQ.Models.KhoanDongGop", b =>
                {
                    b.Property<int>("IdgiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDGiaoDich");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdgiaoDich"));

                    b.Property<bool?>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("IdnguoiTiepNhan")
                        .HasColumnType("int")
                        .HasColumnName("IDNguoiTiepNhan");

                    b.Property<int>("IdnhaHaoTam")
                        .HasColumnType("int")
                        .HasColumnName("IDNhaHaoTam");

                    b.Property<int?>("Idquy")
                        .HasColumnType("int")
                        .HasColumnName("IDQuy");

                    b.Property<string>("LoaiUngHo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayUngHo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("QuyCach")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("SoTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 0)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TenHienVat")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ThanhCong");

                    b.HasKey("IdgiaoDich")
                        .HasName("PK__KhoanDon__5E5A4D81942F33FF");

                    b.HasIndex("IdnguoiTiepNhan");

                    b.HasIndex("IdnhaHaoTam");

                    b.HasIndex("Idquy");

                    b.HasIndex(new[] { "DaXoa" }, "IDX_KhoanDongGop_DaXoa");

                    b.ToTable("KhoanDongGop", null, t =>
                        {
                            t.HasTrigger("trg_KhoanDongGop_AuditQuy");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WebMTTQ.Models.LuotTraoTang", b =>
                {
                    b.Property<int>("IdtraoTang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTraoTang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdtraoTang"));

                    b.Property<bool?>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("IdchuongTrinh")
                        .HasColumnType("int")
                        .HasColumnName("IDChuongTrinh");

                    b.Property<int>("IdnguoiCanGiup")
                        .HasColumnType("int")
                        .HasColumnName("IDNguoiCanGiup");

                    b.Property<int>("IdnguoiCap")
                        .HasColumnType("int")
                        .HasColumnName("IDNguoiCap");

                    b.Property<int?>("Idquy")
                        .HasColumnType("int")
                        .HasColumnName("IDQuy");

                    b.Property<string>("LoaiHoTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayPhanBo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("QuyCach")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("SoTienHoTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 0)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TenHienVat")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdtraoTang")
                        .HasName("PK__LuotTrao__45A28075254501D6");

                    b.HasIndex("IdchuongTrinh");

                    b.HasIndex("IdnguoiCanGiup");

                    b.HasIndex("IdnguoiCap");

                    b.HasIndex("Idquy");

                    b.HasIndex(new[] { "DaXoa" }, "IDX_LuotTraoTang_DaXoa");

                    b.ToTable("LuotTraoTang", null, t =>
                        {
                            t.HasTrigger("trg_LuotTraoTang_AuditQuy");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WebMTTQ.Models.NguoiCanGiupDo", b =>
                {
                    b.Property<int>("IdnguoiCanGiup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDNguoiCanGiup");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdnguoiCanGiup"));

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CCCD");

                    b.Property<bool?>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoanCanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdnguoiCanGiup")
                        .HasName("PK__NguoiCan__92DA5CD99DA55672");

                    b.ToTable("NguoiCanGiupDo");
                });

            modelBuilder.Entity("WebMTTQ.Models.NguoiDung", b =>
                {
                    b.Property<int>("IdnguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDNguoiDung");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdnguoiDung"));

                    b.Property<byte[]>("AnhDaiDien")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool?>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdvaiTro")
                        .HasColumnType("int")
                        .HasColumnName("IDVaiTro");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("HoatDong");

                    b.HasKey("IdnguoiDung")
                        .HasName("PK__NguoiDun__FCD7DB090922A357");

                    b.HasIndex("IdvaiTro");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__NguoiDun__55F68FC0CA9219EA")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiDun__A9D105348E5266DA")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("NguoiDung", null, t =>
                        {
                            t.HasTrigger("trg_NguoiDung_UpdateNgay");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WebMTTQ.Models.NhaHaoTam", b =>
                {
                    b.Property<int>("IdnhaHaoTam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDNhaHaoTam");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdnhaHaoTam"));

                    b.Property<bool?>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LoaiHinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenNguoiUngHo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdnhaHaoTam")
                        .HasName("PK__NhaHaoTa__9835F40B35BF40E3");

                    b.ToTable("NhaHaoTam");
                });

            modelBuilder.Entity("WebMTTQ.Models.NhatKyHeThong", b =>
                {
                    b.Property<int>("IdnhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDNhatKy");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdnhatKy"));

                    b.Property<string>("DiaChiIp")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DiaChiIP");

                    b.Property<string>("DuLieuCu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuLieuMoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdbanGhi")
                        .HasColumnType("int")
                        .HasColumnName("IDBanGhi");

                    b.Property<int?>("IdnguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("IDNguoiDung");

                    b.Property<string>("TenBang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ThoiGianTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("IdnhatKy")
                        .HasName("PK__NhatKyHe__72F501D28C3EF6A3");

                    b.HasIndex("IdnguoiDung");

                    b.ToTable("NhatKyHeThong");
                });

            modelBuilder.Entity("WebMTTQ.Models.ThanhPhanGiaoDien", b =>
                {
                    b.Property<int>("IdthanhPhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDThanhPhan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdthanhPhan"));

                    b.Property<bool?>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("DuongDanLienKet")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<byte[]>("HinhAnh")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Loai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenHienThi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ThuTu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ViTri")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdthanhPhan")
                        .HasName("PK__ThanhPha__90B69433059DBB34");

                    b.ToTable("ThanhPhanGiaoDien");
                });

            modelBuilder.Entity("WebMTTQ.Models.ThongTinNhanUngHo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiNhanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonViThuHuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungChuyenKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QrCodeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNgânHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ThongTinNhanUngHos");
                });

            modelBuilder.Entity("WebMTTQ.Models.VaiTro", b =>
                {
                    b.Property<int>("IdvaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDVaiTro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdvaiTro"));

                    b.Property<bool?>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("QuyenHan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdvaiTro")
                        .HasName("PK__VaiTro__45D3FF49D7A1FDCD");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("WebMTTQ.Models.VanBanTaiLieu", b =>
                {
                    b.Property<int>("IdvanBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDVanBan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdvanBan"));

                    b.Property<string>("CoQuanBanHanh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<double?>("DungLuong")
                        .HasColumnType("float");

                    b.Property<int?>("IdchuyenMuc")
                        .HasColumnType("int")
                        .HasColumnName("IDChuyenMuc");

                    b.Property<string>("LoaiTep")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("NgayBanHanh")
                        .HasColumnType("date");

                    b.Property<string>("SoHieu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenVanBan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("TepDinhKem")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("IdvanBan")
                        .HasName("PK__VanBanTa__FDADF58BFAC3319C");

                    b.HasIndex("IdchuyenMuc");

                    b.HasIndex(new[] { "DaXoa" }, "IDX_VanBan_DaXoa");

                    b.ToTable("VanBanTaiLieu");
                });

            modelBuilder.Entity("WebMTTQ.Models.BaiViet", b =>
                {
                    b.HasOne("WebMTTQ.Models.ChuyenMuc", "IdchuyenMucNavigation")
                        .WithMany("BaiViets")
                        .HasForeignKey("IdchuyenMuc")
                        .HasConstraintName("FK_BaiViet_ChuyenMuc");

                    b.HasOne("WebMTTQ.Models.NguoiDung", "IdnguoiDungNavigation")
                        .WithMany("BaiViets")
                        .HasForeignKey("IdnguoiDung")
                        .HasConstraintName("FK_BaiViet_NguoiDung");

                    b.Navigation("IdchuyenMucNavigation");

                    b.Navigation("IdnguoiDungNavigation");
                });

            modelBuilder.Entity("WebMTTQ.Models.ChuyenMuc", b =>
                {
                    b.HasOne("WebMTTQ.Models.ChuyenMuc", "IdchuyenMucChaNavigation")
                        .WithMany("InverseIdchuyenMucChaNavigation")
                        .HasForeignKey("IdchuyenMucCha")
                        .HasConstraintName("FK_ChuyenMuc_ChuyenMucCha");

                    b.Navigation("IdchuyenMucChaNavigation");
                });

            modelBuilder.Entity("WebMTTQ.Models.DiaDiemBanDo", b =>
                {
                    b.HasOne("WebMTTQ.Models.DoanTheToChuc", "IddonViNavigation")
                        .WithMany("DiaDiemBanDos")
                        .HasForeignKey("IddonVi")
                        .HasConstraintName("FK_DiaDiem_DonVi");

                    b.Navigation("IddonViNavigation");
                });

            modelBuilder.Entity("WebMTTQ.Models.DonXinHoTro", b =>
                {
                    b.HasOne("WebMTTQ.Models.NguoiCanGiupDo", "IdnguoiCanGiupNavigation")
                        .WithMany("DonXinHoTros")
                        .HasForeignKey("IdnguoiCanGiup")
                        .HasConstraintName("FK_DonXin_NguoiCanGiup");

                    b.HasOne("WebMTTQ.Models.NguoiDung", "IdnguoiXuLyNavigation")
                        .WithMany("DonXinHoTros")
                        .HasForeignKey("IdnguoiXuLy")
                        .HasConstraintName("FK_DonXin_NguoiDung");

                    b.Navigation("IdnguoiCanGiupNavigation");

                    b.Navigation("IdnguoiXuLyNavigation");
                });

            modelBuilder.Entity("WebMTTQ.Models.HopThuGopY", b =>
                {
                    b.HasOne("WebMTTQ.Models.NguoiDung", "IdnguoiXuLyNavigation")
                        .WithMany("HopThuGopies")
                        .HasForeignKey("IdnguoiXuLy")
                        .HasConstraintName("FK_GopY_NguoiDung");

                    b.Navigation("IdnguoiXuLyNavigation");
                });

            modelBuilder.Entity("WebMTTQ.Models.KhoanDongGop", b =>
                {
                    b.HasOne("WebMTTQ.Models.NguoiDung", "IdnguoiTiepNhanNavigation")
                        .WithMany("KhoanDongGops")
                        .HasForeignKey("IdnguoiTiepNhan")
                        .IsRequired()
                        .HasConstraintName("FK_DongGop_NguoiDung");

                    b.HasOne("WebMTTQ.Models.NhaHaoTam", "IdnhaHaoTamNavigation")
                        .WithMany("KhoanDongGops")
                        .HasForeignKey("IdnhaHaoTam")
                        .IsRequired()
                        .HasConstraintName("FK_DongGop_NhaHaoTam");

                    b.HasOne("WebMTTQ.Models.DanhMucQuy", "IdquyNavigation")
                        .WithMany("KhoanDongGops")
                        .HasForeignKey("Idquy")
                        .HasConstraintName("FK_DongGop_Quy");

                    b.Navigation("IdnguoiTiepNhanNavigation");

                    b.Navigation("IdnhaHaoTamNavigation");

                    b.Navigation("IdquyNavigation");
                });

            modelBuilder.Entity("WebMTTQ.Models.LuotTraoTang", b =>
                {
                    b.HasOne("WebMTTQ.Models.ChuongTrinhHoTro", "IdchuongTrinhNavigation")
                        .WithMany("LuotTraoTangs")
                        .HasForeignKey("IdchuongTrinh")
                        .IsRequired()
                        .HasConstraintName("FK_TraoTang_ChuongTrinh");

                    b.HasOne("WebMTTQ.Models.NguoiCanGiupDo", "IdnguoiCanGiupNavigation")
                        .WithMany("LuotTraoTangs")
                        .HasForeignKey("IdnguoiCanGiup")
                        .IsRequired()
                        .HasConstraintName("FK_TraoTang_NguoiCanGiup");

                    b.HasOne("WebMTTQ.Models.NguoiDung", "IdnguoiCapNavigation")
                        .WithMany("LuotTraoTangs")
                        .HasForeignKey("IdnguoiCap")
                        .IsRequired()
                        .HasConstraintName("FK_TraoTang_NguoiDung");

                    b.HasOne("WebMTTQ.Models.DanhMucQuy", "IdquyNavigation")
                        .WithMany("LuotTraoTangs")
                        .HasForeignKey("Idquy")
                        .HasConstraintName("FK_TraoTang_Quy");

                    b.Navigation("IdchuongTrinhNavigation");

                    b.Navigation("IdnguoiCanGiupNavigation");

                    b.Navigation("IdnguoiCapNavigation");

                    b.Navigation("IdquyNavigation");
                });

            modelBuilder.Entity("WebMTTQ.Models.NguoiDung", b =>
                {
                    b.HasOne("WebMTTQ.Models.VaiTro", "IdvaiTroNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("IdvaiTro")
                        .HasConstraintName("FK_NguoiDung_VaiTro");

                    b.Navigation("IdvaiTroNavigation");
                });

            modelBuilder.Entity("WebMTTQ.Models.NhatKyHeThong", b =>
                {
                    b.HasOne("WebMTTQ.Models.NguoiDung", "IdnguoiDungNavigation")
                        .WithMany("NhatKyHeThongs")
                        .HasForeignKey("IdnguoiDung")
                        .HasConstraintName("FK_NhatKy_NguoiDung");

                    b.Navigation("IdnguoiDungNavigation");
                });

            modelBuilder.Entity("WebMTTQ.Models.VanBanTaiLieu", b =>
                {
                    b.HasOne("WebMTTQ.Models.ChuyenMuc", "IdchuyenMucNavigation")
                        .WithMany("VanBanTaiLieus")
                        .HasForeignKey("IdchuyenMuc")
                        .HasConstraintName("FK_VanBan_ChuyenMuc");

                    b.Navigation("IdchuyenMucNavigation");
                });

            modelBuilder.Entity("WebMTTQ.Models.ChuongTrinhHoTro", b =>
                {
                    b.Navigation("LuotTraoTangs");
                });

            modelBuilder.Entity("WebMTTQ.Models.ChuyenMuc", b =>
                {
                    b.Navigation("BaiViets");

                    b.Navigation("InverseIdchuyenMucChaNavigation");

                    b.Navigation("VanBanTaiLieus");
                });

            modelBuilder.Entity("WebMTTQ.Models.DanhMucQuy", b =>
                {
                    b.Navigation("KhoanDongGops");

                    b.Navigation("LuotTraoTangs");
                });

            modelBuilder.Entity("WebMTTQ.Models.DoanTheToChuc", b =>
                {
                    b.Navigation("DiaDiemBanDos");
                });

            modelBuilder.Entity("WebMTTQ.Models.NguoiCanGiupDo", b =>
                {
                    b.Navigation("DonXinHoTros");

                    b.Navigation("LuotTraoTangs");
                });

            modelBuilder.Entity("WebMTTQ.Models.NguoiDung", b =>
                {
                    b.Navigation("BaiViets");

                    b.Navigation("DonXinHoTros");

                    b.Navigation("HopThuGopies");

                    b.Navigation("KhoanDongGops");

                    b.Navigation("LuotTraoTangs");

                    b.Navigation("NhatKyHeThongs");
                });

            modelBuilder.Entity("WebMTTQ.Models.NhaHaoTam", b =>
                {
                    b.Navigation("KhoanDongGops");
                });

            modelBuilder.Entity("WebMTTQ.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
